const $=s=>document.querySelector(s),app=$('#app');
const store={get:k=>JSON.parse(localStorage.getItem('riyo_'+k)||'null'),set:(k,v)=>localStorage.setItem('riyo_'+k,JSON.stringify(v))};
let state={page:'home',category:null,session:[],idx:0,selected:null,answered:false,search:''};
const prog=()=>store.get('prog')||{done:{},wrong:{},fav:{},history:[]};
const save=p=>store.set('prog',p);
const pct=(n,d)=>d?Math.round(n/d*100):0;
const qsCat=id=>QUESTIONS.filter(q=>q.category===id);
const qsSub=id=>QUESTIONS.filter(q=>q.subject===id);
const sub=id=>SUBJECTS.find(s=>s.id===id);
const cat=id=>CATEGORIES.find(c=>c.id===id);
const jpNo=['①','②','③','④'];
function route(page,extra={}){state={...state,page,...extra,selected:null,answered:false};render()}
function bottom(active){return `<nav class="bottom"><button class="${active==='home'?'on':''}" onclick="route('home')">⌂<span>ホーム</span></button><button class="${active==='random'?'on':''}" onclick="startRandom()">☷<span>ランダム出題</span></button><button class="${active==='review'?'on':''}" onclick="route('review')">☰<span>苦手一覧</span></button><button class="${active==='score'?'on':''}" onclick="route('score')">▥<span>成績</span></button><button class="${active==='settings'?'on':''}" onclick="route('settings')">⚙<span>設定</span></button></nav>`}
function header(title='理容師国家試験対策',back=false){return `<header class="top">${back?`<button onclick="route('home')">‹</button>`:`<button>☰</button>`}<h1>${title}</h1><button onclick="route('search')">⌕</button></header>`}
function home(){const p=prog();return `<main>${header()}<section class="content"><h2>法令一覧</h2><div class="list">${CATEGORIES.map((c,i)=>{let qs=qsCat(c.id),d=qs.filter(q=>p.done[q.id]).length,imp=qs.filter(q=>q.importance>=4).length,clr=sub(c.subject).color;return `<button class="law" onclick="startCategory('${c.id}')"><span class="num" style="background:${clr}">${i+1}</span><span class="grow"><span>${i+1<=9?'':i+1+'　'}${c.name}</span><small>学習済み　${d}/${qs.length}</small></span><span class="imp">${imp} 重要 ›</span></button>`}).join('')}</div>${progressCard(p)}</section>${bottom('home')}</main>`}
function progressCard(p){let done=Object.keys(p.done).length,wrong=Object.keys(p.wrong).length,imp=QUESTIONS.filter(q=>q.importance>=4),impDone=imp.filter(q=>p.done[q.id]).length,doneCats=CATEGORIES.filter(c=>qsCat(c.id).every(q=>p.done[q.id])).length;return `<section class="progress"><h2>学習の進捗</h2><div class="progress-body"><div class="ring" style="--p:${pct(done,QUESTIONS.length)}"><span>${pct(done,QUESTIONS.length)}%</span><small>全体の進捗</small></div><div class="progress-list"><button onclick="route('score')"><span>□　学習済み条文</span><span>${done} / ${QUESTIONS.length} ›</span></button><button onclick="route('score')"><span>☆　重要条文</span><span>${impDone} / ${imp.length} ›</span></button><button onclick="route('review')"><span>△　苦手条文</span><span>${wrong} ›</span></button><button onclick="route('score')"><span>⚖　学習済み法令</span><span>${doneCats} / ${CATEGORIES.length} ›</span></button></div></div></section>`}
function startCategory(id){let qs=qsCat(id).sort((a,b)=>b.importance-a.importance);state.session=qs;route('question',{category:id,idx:0})}
function startRandom(){state.session=[...QUESTIONS].sort(()=>Math.random()-.5);route('question',{idx:0})}
function question(){let q=state.session[state.idx]||QUESTIONS[0],c=cat(q.category),s=sub(q.subject);return `<main>${header(`第${state.idx+1}問 / ${state.session.length}問`,true)}<section class="content"><div class="qcard"><div class="qmeta"><span>${s.name} ＞ ${c.name}</span><span>重要度 ${'★'.repeat(q.importance)}</span></div><p class="qtext">${q.q}</p>${q.choices.map((ch,i)=>{let cls=state.selected===i?'sel':'';if(state.answered&&i===q.answer)cls+=' ok';if(state.answered&&state.selected===i&&i!==q.answer)cls+=' ng';return `<button class="choice ${cls}" onclick="select(${i})"><span>${jpNo[i]}</span>${ch}</button>`}).join('')}<button class="primary" onclick="answer()">解答する</button></div>${state.answered?answerBox(q):''}</section>${bottom('home')}</main>`}
function answerBox(q){let ok=state.selected===q.answer;return `<div class="qcard answer"><h2>${ok?'正解です':'確認しましょう'}</h2><p>正解　${jpNo[q.answer]}</p><hr><p>解説</p><p>${q.exp}</p><div class="point">覚えるポイント<br>${q.point}</div><div class="actions"><button onclick="markAgain(${q.id})">もう一度解く</button><button onclick="nextQ()">次の問題へ</button></div></div>`}
function select(i){if(!state.answered){state.selected=i;render()}}
function answer(){if(state.selected===null)return;let q=state.session[state.idx],p=prog(),ok=state.selected===q.answer;p.done[q.id]=true;if(ok)delete p.wrong[q.id];else p.wrong[q.id]=true;p.history.push({id:q.id,ok,day:new Date().toISOString().slice(0,10)});save(p);state.answered=true;render()}
function markAgain(id){let p=prog();p.wrong[id]=true;save(p);nextQ()}
function nextQ(){state.idx<state.session.length-1?route('question',{idx:state.idx+1}):route('score')}
function review(){let p=prog(),qs=QUESTIONS.filter(q=>p.wrong[q.id]);return `<main>${header('苦手一覧',true)}<section class="content">${qs.length?qs.map(q=>`<button class="law" onclick="state.session=[QUESTIONS.find(x=>x.id===${q.id})];route('question',{idx:0})"><span class="num">!</span><span class="grow"><span>${cat(q.category).name}</span><small>${q.q}</small></span><span>解く ›</span></button>`).join(''):`<div class="empty">苦手問題はありません。</div>`}</section>${bottom('review')}</main>`}
function searchPage(){let t=state.search,qs=t?QUESTIONS.filter(q=>(q.q+q.exp+q.point+cat(q.category).name).includes(t)):[];return `<main>${header('検索',true)}<section class="content"><input class="search" placeholder="キーワードで検索" value="${t}" oninput="state.search=this.value;render()">${qs.map(q=>`<button class="law" onclick="state.session=[QUESTIONS.find(x=>x.id===${q.id})];route('question',{idx:0})"><span class="num">⌕</span><span class="grow"><span>${cat(q.category).name}</span><small>${q.q}</small></span><span>›</span></button>`).join('')}</section>${bottom('home')}</main>`}
function score(){let p=prog(),h=p.history,ok=h.filter(x=>x.ok).length;return `<main>${header('成績',true)}<section class="content">${progressCard(p)}<div class="qcard"><h2>正答率</h2><p class="score">${pct(ok,h.length)}%</p><p>${ok} / ${h.length}</p></div>${SUBJECTS.map(s=>{let qs=qsSub(s.id),d=qs.filter(q=>p.done[q.id]).length;return `<div class="subject-row"><span>${s.name}</span><span>${d}/${qs.length}</span></div>`}).join('')}</section>${bottom('score')}</main>`}
function settings(){return `<main>${header('設定',true)}<section class="content"><div class="qcard"><p>学習データは、この端末のブラウザに保存されます。</p><button class="danger" onclick="localStorage.clear();route('home')">学習データをリセット</button></div></section>${bottom('settings')}</main>`}
function render(){app.innerHTML=({home,question,review,search:searchPage,score,settings}[state.page]||home)()}
render();
