const fields = [...new Set(window.QUESTIONS.map(q=>q.field))];
const stateKey='riyoushi_exam_state_v2';
let state=JSON.parse(localStorage.getItem(stateKey)||'{"answers":{},"bookmarks":[]}');
let currentField='全分野'; let mode='all'; let searchText='';
const kana=['①','②','③','④'];
function save(){localStorage.setItem(stateKey,JSON.stringify(state));}
function z(n){return String(n).replace(/[0-9]/g,d=>'０１２３４５６７８９'[d]);}
function rate(){const ids=Object.keys(state.answers); if(!ids.length)return '０％'; const ok=ids.filter(id=>state.answers[id].correct).length; return z(Math.round(ok/ids.length*100))+'％';}
function updateStats(){const ans=Object.keys(state.answers); document.getElementById('answered').textContent=z(ans.length); document.getElementById('correctRate').textContent=rate(); document.getElementById('bookmarked').textContent=z(state.bookmarks.length); document.getElementById('wrongCount').textContent=z(ans.filter(id=>!state.answers[id].correct).length);}
function makeFieldButtons(){const box=document.getElementById('fieldButtons'); box.innerHTML=''; fields.forEach(f=>{const c=window.QUESTIONS.filter(q=>q.field===f).length; const b=document.createElement('button'); b.className='fieldBtn'+(currentField===f?' active':''); b.innerHTML=`<strong>${f}</strong><span>${z(c)}問</span>`; b.onclick=()=>{currentField=f;mode='field';render();}; box.appendChild(b);});}
function targetQuestions(){let arr=[...window.QUESTIONS]; if(mode==='field') arr=arr.filter(q=>q.field===currentField); if(mode==='bookmarks') arr=arr.filter(q=>state.bookmarks.includes(q.id)); if(searchText) arr=arr.filter(q=>(q.question+q.topic+q.field).includes(searchText)); return arr;}
function render(){makeFieldButtons(); updateStats(); const title=document.getElementById('currentTitle'); const summary=document.getElementById('currentSummary'); if(mode==='bookmarks'){title.textContent='ブックマーク';} else {title.textContent=currentField;} const arr=targetQuestions(); summary.textContent='問題をタップすると開きます。'; const box=document.getElementById('questions'); box.innerHTML=''; if(!arr.length){box.innerHTML='<div class="panel empty">該当する問題はありません。</div>'; return;} arr.forEach(q=>box.appendChild(card(q)));}
function card(q){const div=document.createElement('article'); div.className='qcard'; const answered=state.answers[q.id]; const bm=state.bookmarks.includes(q.id); div.innerHTML=`<button class="qhead"><div><div class="qmeta">第${z(q.id)}問　${q.field}　｜　${q.topic}</div><div class="qtitle">${q.question}</div></div><span class="badge">開く</span></button><div class="qbody"><div class="choices"></div><div class="row"><button class="mini soft showAnswer">正解・解説を表示</button><button class="mini soft bookmark ${bm?'on':''}">${bm?'保存済み':'ブックマーク'}</button></div><div class="explain"><strong>正解：${kana[q.answer]}</strong><br>${q.explanation}</div></div>`; div.querySelector('.qhead').onclick=()=>div.classList.toggle('open'); const choices=div.querySelector('.choices'); q.choices.forEach((ch,i)=>{const b=document.createElement('button'); b.className='choice'; b.textContent=`${kana[i]}　${ch}`; if(answered){ if(i===q.answer)b.classList.add('correct'); if(answered.choice===i && i!==q.answer)b.classList.add('wrong'); } b.onclick=()=>{state.answers[q.id]={choice:i,correct:i===q.answer}; save(); div.querySelectorAll('.choice').forEach((x,j)=>{x.classList.remove('correct','wrong'); if(j===q.answer)x.classList.add('correct'); if(j===i && j!==q.answer)x.classList.add('wrong');}); div.querySelector('.explain').classList.add('show'); updateStats();}; choices.appendChild(b);}); div.querySelector('.showAnswer').onclick=()=>div.querySelector('.explain').classList.toggle('show'); div.querySelector('.bookmark').onclick=(e)=>{const idx=state.bookmarks.indexOf(q.id); if(idx>=0)state.bookmarks.splice(idx,1); else state.bookmarks.push(q.id); save(); render();}; return div;}
document.getElementById('search').oninput=e=>{searchText=e.target.value.trim();render();};
document.getElementById('showAll').onclick=()=>{mode='all';currentField='全分野';render();};
document.getElementById('showBookmarks').onclick=()=>{mode='bookmarks';currentField='ブックマーク';render();};
document.getElementById('wrongRandom').onclick=()=>{const wrong=Object.keys(state.answers).filter(id=>!state.answers[id].correct).map(Number); if(!wrong.length){alert('誤答がまだありません。');return;} const id=wrong[Math.floor(Math.random()*wrong.length)]; const q=window.QUESTIONS.find(x=>x.id===id); currentField=q.field; mode='field'; searchText=q.question.slice(0,12); document.getElementById('search').value=searchText; render(); setTimeout(()=>document.querySelector('.qcard')?.classList.add('open'),50);};
document.getElementById('resetProgress').onclick=()=>{if(confirm('解答記録とブックマークを消去しますか？')){state={answers:{},bookmarks:[]};save();render();}};
render();
